language: ruby

dist: xenial

before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

cache:
  bundler: true

jobs:
  include:
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: ruby-head
    - rvm: 2.7.1
      name: "RuboCop"
      before_install: []
      script: bundle exec rubocop
  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - master
