sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0

before_install:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

branches:
  only:
    - master
