sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0

before_install:
  - rvm use @global
  - gem uninstall bundler -x
  - gem install bundler --version=1.13.7
  - bundler --version

branches:
  only:
    - master
