sudo: false
language: ruby

before_install:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - gem update --system

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - master
