language: ruby

dist: xenial

before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

cache:
  bundler: true

rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - master
